/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_message_2eproto__INCLUDED
#define PROTOBUF_C_message_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _ServerCommand ServerCommand;


/* --- enums --- */

typedef enum _ServerCommand__Command {
  SERVER_COMMAND__COMMAND__NOP = 0,
  SERVER_COMMAND__COMMAND__START = 1,
  SERVER_COMMAND__COMMAND__DISCONNECT = 20
} ServerCommand__Command;

/* --- messages --- */

struct  _ServerCommand
{
  ProtobufCMessage base;
  ServerCommand__Command command_id;
};
#define SERVER_COMMAND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&server_command__descriptor) \
    , 0 }


/* ServerCommand methods */
void   server_command__init
                     (ServerCommand         *message);
size_t server_command__get_packed_size
                     (const ServerCommand   *message);
size_t server_command__pack
                     (const ServerCommand   *message,
                      uint8_t             *out);
size_t server_command__pack_to_buffer
                     (const ServerCommand   *message,
                      ProtobufCBuffer     *buffer);
ServerCommand *
       server_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   server_command__free_unpacked
                     (ServerCommand *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ServerCommand_Closure)
                 (const ServerCommand *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor server_command__descriptor;
extern const ProtobufCEnumDescriptor    server_command__command__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_message_2eproto__INCLUDED */
